import { Beef, Bone, CarrotIcon, CheckCircle, Droplet, Fish, Flower2, Leaf, MilkOff, Nut, Salad, Scale, Wheat } from "lucide-react";
export const QUESTIONS = [
    {
      id: "location",
      title: "Where are you located?",
      subtitle: "We'll find the perfect spots near you",
      type: "text",
      placeholder: "Enter your city or location...",
      icon: "📍",
    },
    {
      id: "vibes",
      title: "What's your ideal vibe?",
      subtitle: "Pick all that apply - we love variety!",
      type: "multiple",
      options: [
        { id: "romantic", label: "Romantic", icon: "💕" },
        { id: "adventurous", label: "Adventurous", icon: "🏔️" },
        { id: "chill", label: "Chill", icon: "😌" },
        { id: "luxe", label: "Luxe", icon: "✨" },
        { id: "nature", label: "Nature", icon: "🌿" },
        { id: "artsy", label: "Artsy", icon: "🎨" },
        { id: "goofy", label: "Goofy", icon: "🤪" },
      ],
    },
    // {
    //   id: "dietary",
    //   title: "Any dietary preferences?",
    //   subtitle: "We'll make sure you have delicious options",
    //   placeholder: "e.g., vegetarian, gluten-free, no restrictions...",
    //   icon: "🍽️",
    //   type: "multiple",
    //   options: [
    //     { "id": "milk", "label": "Milk", "icon": <Milk /> },
    //     { "id": "eggs", "label": "Eggs", "icon": <Egg /> },
    //     { "id": "peanuts", "label": "Peanuts", "icon": <Nut /> },
    //     { "id": "tree_nuts", "label": "Tree Nuts", "icon": <Nut /> },
    //     { "id": "wheat", "label": "Wheat", "icon": <Wheat /> },
    //     { "id": "soy", "label": "Soy", "icon": <Bean /> },
    //     { "id": "fish", "label": "Fish", "icon": <Fish /> },
    //     { "id": "shellfish", "label": "Shellfish", "icon": <Shell /> },
    //     { "id": "sesame", "label": "Sesame", "icon": <Bean /> },
    //     { "id": "gluten", "label": "Gluten", "icon": <Wheat /> },
    //     { "id": "lactose", "label": "Lactose", "icon": <MilkOff /> },
    //     { "id": "vegetarian", "label": "Vegetarian", "icon": <Leaf /> },
    //     { "id": "vegan", "label": "Vegan", "icon": <Leaf /> },
    //     { "id": "kosher", "label": "Kosher", "icon": <ChefHat /> },
    //     { "id": "halal", "label": "Halal", "icon": <MoonStar /> },
    //     { "id": "no_pork", "label": "No Pork", "icon": <PiggyBank /> },
    //     { "id": "no_beef", "label": "No Beef", "icon": <Beef /> },
    //     { "id": "diabetes_friendly", "label": "Diabetes Friendly", "icon": <Droplets /> },
    //     { "id": "paleo", "label": "Paleo", "icon": <Bone /> },
    //     { "id": "keto", "label": "Keto", "icon": <Droplet /> },
    //     { "id": "raw_food", "label": "Raw Food", "icon": <Salad /> },
    //     { "id": "alpha_gal", "label": "Alpha-gal Syndrome", "icon": <BugOff /> },
    //   ],
    // },
    {
      id: "dietary",
      title: "Any dietary preferences?",
      subtitle: "We'll make sure you have delicious options",
      placeholder: "e.g., vegetarian, gluten-free, no restrictions...",
      icon: "🍽️",
      type: "multiple",
      options: [
          { "id": "vegetarian", "label": "Vegetarian", "icon": <Leaf /> },
          { "id": "vegan", "label": "Vegan", "icon": <Leaf /> },
          { "id": "pescetarian", "label": "Pescetarian", "icon": <Fish /> },
          { "id": "paleo", "label": "Paleo", "icon": <Bone /> },
          { "id": "keto", "label": "Keto", "icon": <Droplet /> },
          { "id": "raw_food", "label": "Raw Food", "icon": <Salad /> },
          { "id": "flexitarian", "label": "Flexitarian", "icon": <Scale /> },
          { "id": "dairy_free", "label": "Dairy-Free (Preference)", "icon": <MilkOff /> },
          { "id": "gluten_free_preference", "label": "Gluten-Free (Preference)", "icon": <Wheat /> },
          { "id": "low_carb", "label": "Low Carb", "icon": <CarrotIcon /> },
          { "id": "whole30", "label": "Whole30", "icon": <CheckCircle /> },
          { "id": "mediterranean", "label": "Mediterranean", "icon": <Nut /> },
          { "id": "no_red_meat", "label": "No Red Meat", "icon": <Beef /> },
          { "id": "plant_based", "label": "Plant-Based", "icon": <Flower2 /> }
      ],
    },
    {
      id: "budget",
      title: "What's your budget?",
      subtitle: "Great dates happen at every price point",
      type: "single",
      options: [
        { id: "free", label: "Free", icon: "💝", desc: "No cost activities" },
        { id: "low", label: "$", icon: "💰", desc: "Under $50 total" },
        { id: "medium", label: "$$", icon: "💰💰", desc: "Under $100 total" },
        { id: "high", label: "$$$", icon: "💳", desc: "Under $200 total" },
      ],
    },
    {
      id: "timeframe",
      title: "When are you planning this?",
      subtitle: "We'll suggest options based on timing",
      type: "single",
      options: [
        {
          id: "tonight",
          label: "Tonight",
          icon: "🌙",
          desc: "Last-minute magic",
        },
        {
          id: "weekend",
          label: "This Weekend",
          icon: "🗓️",
          desc: "Weekend vibes",
        },
        { id: "next-week", label: "Next Week", icon: "📅", desc: "Plan ahead" },
        {
          id: "future",
          label: "Plan Ahead",
          icon: "🔮",
          desc: "Future planning",
        },
      ],
    },
    {
      id: "duration",
      title: "How much time do you have?",
      subtitle: "We'll match activities to your schedule",
      type: "single",
      options: [
        { id: "quick", label: "Quick Hour", icon: "⏰", desc: "1-2 hours" },
        { id: "evening", label: "Evening Out", icon: "🌆", desc: "3-5 hours" },
        { id: "full-day", label: "Full Day", icon: "☀️", desc: "6+ hours" },
      ],
    },
    {
      id: "celebration",
      title: "Celebrating something special?",
      subtitle: "We'll add extra magic to your suggestions",
      type: "text",
      placeholder: "e.g., anniversary, birthday, or just because...",
      icon: "🎉",
    },
    // {
    //   id: "involvement",
    //   title: "Planning preference?",
    //   subtitle: "How involved do you want to be?",
    //   type: "single",
    //   options: [
    //     {
    //       id: "surprise",
    //       label: "Surprise Me!",
    //       icon: "🎁",
    //       desc: "Full surprise planning",
    //     },
    //     {
    //       id: "collaborate",
    //       label: "Let's Plan Together",
    //       icon: "🤝",
    //       desc: "Collaborative planning",
    //     },
    //     {
    //       id: "control",
    //       label: "I Want Control",
    //       icon: "🎯",
    //       desc: "Detailed planning",
    //     },
    //   ],
    // },
    {
      id: "dislikes",
      title: "What dates do you NOT enjoy?",
      subtitle: "We'll steer clear of these completely",
      type: "text",
      placeholder: "e.g., crowded places, loud music, heights...",
      icon: "🚫",
    },
    {
      id: "activityLevel",
      title: "How active do you want to be?",
      subtitle: "Match the energy to your mood",
      type: "single",
      options: [
        {
          id: "relaxed",
          label: "Relaxed",
          icon: "🧘‍♀️",
          desc: "Calm and peaceful",
        },
        { id: "medium", label: "Medium", icon: "🧗", desc: "Some movement" },
        {
          id: "energetic",
          label: "Energetic",
          icon: "🕺",
          desc: "High energy fun",
        },
      ],
    },
  ];
  