export enum DateTypeCategory {
  Romantic = "romantic",
  Fun = "fun",
  Adventurous = "adventurous",
  Relaxing = "relaxing",
  Unique = "unique",
  Cultural = "cultural",
  Seasonal = "seasonal",
  Foodie = "foodie",
  Outdoor = "outdoor",
  Indoor = "indoor",
  Creative = "creative",
  BudgetFriendly = "budget-friendly",
  Luxury = "luxury",
  LastMinute = "last-minute",
  WeekendGetaway = "weekend-getaway",
  SpecialOccasion = "special-occasion",
  GroupActivity = "group-activity",
}
